# Default configuration for CMVec2Vec

[model]
embedding_dim = 1536
latent_dim = 256
hidden_dim = 512
adapter_depth = 3
backbone_depth = 4
dropout = 0.1
use_conditioning = false
normalize_embeddings = true
weight_init = "kaiming"
activation = "silu"

[training]
lr_generator = 1e-4
lr_discriminator = 4e-4
epochs = 100
batch_size = 32
device = "cuda"
weight_decay = 0.01
max_grad_norm = 1.0
use_scheduler = true
warmup_steps = 1000
early_stopping_patience = 20

[loss_weights]
reconstruction = 15.0
cycle_consistency = 15.0
vsp = 2.0
adversarial = 1.0
latent_adversarial = 1.0

[data]
data_path = ""
test_size = 0.2
random_state = 42
normalize = true
noise_level = 0.01

[logging]
save_dir = "checkpoints"
save_every = 10